site_name: Pygame + Min-Max

theme:
  feature:
    tabs: true
  name: material

docs_dir: content
site_dir: docs

site_url: https://fbarth.github.io/Connect4-Python/
repo_name: "Connect4-Python"
repo_url: https://github.com/fbarth/Connect4-Python
edit_uri: edit/main/content/

nav:
  - Introdução: index.md
  - Jogando entre humanos: parte1.md 
  - Colocando um robô na partida: parte2.md
  - Implementando um jogador de verdade: parte3.md
  - Implementando um robô ainda melhor: parte4.md
  - Algoritmo Min-Max (parte 1): parte5.md
  - Algoritmo Min-Max (parte 2): parte6.md
  - Instalação e configuração: configuracao.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - js/markdown-enhancer.js

markdown_extensions:
  - admonition
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - git-revision-date-localized
#  - active-exercises:
#      report_url: http://localhost:8000/api/offerings/1/exercises/

